### ISSUE TITLE
Problems with the plotV function

### ISSUE THREAD

**Issue by naiarabediaga** [GreenleafLab/NucleoATACR#1]
Hi Alicia, 

Fits of all I would like to thank you for both NucleoATAC and NucleoATACR packages... I was trying to make some plots using the example files in the NucleoATACR before proceeding with my own data, and I get the following error when I try to plot the "relative insertion probabilities" with respect to the "position relative to dyad" using the function plotV. 

Any help would be greatly appreciated!

Thanks so much!
--------------------
devtools::install_github("GreenleafLab/testthat")
library(NucleoATACR)

##Read in vplot and plot:
  
v <- read_vplot("test.VMat")
plotV(v)

Error in FUN(X[[i]], ...) : 
  Theme element 'text' has NULL property: margin, debug
In addition: Warning messages:
1: `axis.ticks.margin` is deprecated. Please set `margin` property  of `axis.text` instead 
2: `panel.margin` is deprecated. Please use `panel.spacing` property instead 
3: `legend.margin` must be specified using `margin()`. For the old behavior use legend.spacing

**Comment by maltesemike** [comment]
Hi Alicia

Also a big thanks for NucleoATAC and NucleoATACR...

I was also just about to post the very same issue I am having!

From my google search it appears to somehow relate to version changes in ggplot2.. but I'm not proficient enough to determine exactly what.

Hope you can help soon. Find below the session info...

Thanks

> sessionInfo()
> R version 3.3.1 (2016-06-21)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.0   pheatmap_1.0.8  NucleoATACR_1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7        assertthat_0.1     grid_3.3.1         plyr_1.8.4         gtable_0.2.0       magrittr_1.5       scales_0.4.1  
 [8] stringi_1.1.2      reshape2_1.4.2     lazyeval_0.2.0     RColorBrewer_1.1-2 tools_3.3.1        stringr_1.1.0      munsell_0.4.3  
[15] colorspace_1.3-0   tibble_1.2

**Comment by maltesemike** [comment]
Hi again

After some tweaking of the vplot.R code, I came up with a fix that solves the issues for plotting. I have created a pull request for you to look at. Hopefully this will save you time fixing it yourself and also help others in the community.

I am also happy with myself, this is my first bit of decoding! Baby steps and all..

Thanks

**Comment by AliciaSchep** [comment]
Yes, this seems issue with version of ggplot2, the theme arguments changed in latest versions.  I will take a look at the pull request & probably accept it!

**Comment by AliciaSchep** [comment]
Fixed by #2 , thanks @maltesemike !
