### ISSUE TITLE
readNucs error

### ISSUE THREAD

**Issue by DoaneAS** [GreenleafLab/NucleoATACR#4]
Hi,  

Seeing this error with recent update: 

```
> nucs <- readNucs("Sample_NB.nucmap_combined.bed.gz")
Error in cols(chr = col_character()) : could not find function "cols"
```

Maybe a namespace issue, will take a look.

**Comment by AliciaSchep** [comment]
Thanks for PR -- I will take a look and likely merge soon.

**Comment by DoaneAS** [comment]
Sure, thank you!
